import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";
import { Suspense } from "react";
import Loading from "./loading";
import { SearchProvider } from "@/context/SearchContext";

const open_Sans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pinterest Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open_Sans.className}>
        <AuthProvider>
          <SearchProvider>
            <Navbar />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
